title: Emory data science Club

description: Representing Emory University of Atlanta's undergraduate students club members.
Specializing in mathematics, computer science, statistics

social:
    links:
        - https://www.facebook.com/emory.datascience/
        - https://twitter.com/QuanTMEmory
        - https://www.quantitative.emory.edu


plugins:
    - jekyll-seo-tag
