title: Emory data science Club

description: a website representing emory university of atlanta's undergraduate students club members specialize in mathematics, computer science, statistics

plugins:
    - jekyll-seo-tag
